---
# tasks file for cassandra_node

- name: Update all security-related local packages to latest versions.
  yum:
    name: "*"
    update_cache: yes
    security: yes
    state: latest

- name: Install OpenJDK 1.8
  yum:
    name: java-1.8.0-openjdk
    state: "{{ jdk_version }}"

- name: Create Cassandra group.
  group:
    name: cassandra
    state: present

- name: Create Cassandra user.
  user:
    name: cassandra
    group: cassandra
    comment: "Cassandra service user"

- name: Check if Cassandra is installed.
  stat:
    path: /usr/local/cassandra
  register: cass_dir

- name: Copy Cassandra
  unarchive:
    src: "{{ cassandra_tgz_src }}"
    dest: /usr/local/
    remote_src: yes
  when: not cass_dir.stat.exists

- name: Locate extracted Cassandra directory.
  find:
    file_type: directory
    paths: /usr/local
    patterns: apache-cassandra-*
  register: cass_inst_dir

- name: Rename Cassandra installation directory.
  command: mv {{ cass_inst_dir.files.0['path'] }} /usr/local/cassandra
  when: cass_inst_dir.matched == 1

- name: Create Cassandra data directory.
  file:
    path: /usr/local/cassandra/data
    state: directory
    mode: 0755
    owner: cassandra
    group: cassandra
  when: cass_inst_dir.matched == 1

- name: Ensure correct ownership of Cassandra program data.
  file:
    path: /usr/local/cassandra
    state: directory
    mode: 0755
    owner: cassandra
    group: cassandra

- name: Install Cassandra systemd service
  template:
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
    owner: root
    group: root
    mode: '0755'

- name: Ensure max_map_count is sufficiently high for Cassandra to function.
  sysctl:
    name: vm.max_map_count
    value: 1048575
    state: present

- name: Install Cassandra configuration files
  template:
    src: cass-configuration.yml.j2
    dest: /usr/local/cassandra/conf/cassandra.yaml
    owner: cassandra
    group: cassandra
    mode: '0755'

- name: Enable and start Cassandra service
  systemd:
    name: cassandra.service
    daemon_reload: yes
    enabled: yes
    state: started
